/**
 * Paired lists for recipe editor presence monikers — keep in sync with random-name-generator.html.
 */
(function (global) {
  'use strict';

  global.NAME_DECK_LIST_A = [
    'A.',
    'Abbess',
    'Abbot',
    'Archangel',
    '',
    '',
    '',
    '',
    '',
    'Administrator',
    'Admiral',
    'Archdeacon',
    'Mademoiselle',
    'Artificer',
    'P.',
    'Bailiff',
    'Herr',
    'Beekeeper',
    'Sensei',
    'Senator',
    'Minor Deity',
    'Brother',
    'Captain',
    'Vizier',
    'Chancellor',
    'The Illustrious',
    'Colonel',
    'Commander',
    'Daddy',
    'Joe',
    'Commodore',
    'Constable',
    'Corporal',
    'Tsar',
    'Director',
    'E.',
    'Emperor',
    'Employee-of-the-Month',
    'Ensign',
    'Falconer',
    'Doña',
    'Friar',
    'G.',
    'Tough Guy',
    'General',
    'Groundskeeper',
    'Her Majesty, Queen',
    'Penitent',
    'Headmaster',
    'Headmistress',
    'Madame',
    'M.',
    'Bhagwan',
    'Librarian',
    'Lieutenant',
    'Magistrate',
    'Major',
    'Marshal',
    'Pallbearer',
    'Overseer',
    'Prefect',
    'His Grace, Pope',
    'Provost',
    'Quartermaster',
    'R.',
    'O.',
    'Attendant',
    'Sergeant',
    'Sister',
    'Nurse',
    'Night Nurse',
    'Janissary',
    'Governor',
    'Steward',
    'Superintendent',
    'Surveyor',
    'T.',
    'Troubadour',
    'Vicar',
    'Viscount',
    'Viceroy',
    'Den Mother',
    'Kid',
    'Inmate',
    'Baby Jane',
    'Old Man',
    'Reverend',
    'Bürgermeister',
    'Squire',
    'Sultan',
    'W.',
    'Advokat',
    'Warden',
    'Watchman',
    'Boss Man',
    'Lil\u2019 Guy',
    'Monsieur',
    'Lady',
    'Sir',
    'Shri',
    'Master',
    'Saint',
    'Monsignor',
    'Señor',
    'Duchess',
    'Professor',
    'Person-of-Interest',
    'Jephthah',
    'Señora',
    'Oyabun',
    'Señorita',
    'Prince',
    'Princess',
    'Lady-in-Waiting',
    'Regent',
    'Sovereign',
    'Prime Minister',
    'Caliph',
    'Uncle',
    'Wazir',
    'Ringmaster',
    'Funeral Singer',
    'Député',
    'Adept',
    'Consort',
    'Inquisitor',
    'Queen Consort',
    'Cardinal',
    'King Consort',
    'Commander-in-Exile',
    'Count',
    'Elder',
    'Premier',
    'Champion',
    'Archduke',
    'Citizen',
    'Queen Mother',
    'Summoner',
    'Archon',
    'Ombudsman',
    'Her Honour',
    'The Right Honourable',
    'Hierophant',
    'Grandee',
  ];

  global.NAME_DECK_LIST_B = [
    '\u201CFatty\u201D Hammerfist',
    '\u201CGuvnor\u201D Grapefield',
    'P. Dunwitty',
    'Abramov-Ping',
    'T. Cakes',
    'Beancake',
    'Ringleader',
    'Strongarm',
    'Beekeeper',
    'Doe',
    '[Last Name Withheld]',
    'Ackbar',
    'Campion',
    'Krennic',
    'Bisquick III',
    'Bellringer',
    'Moue',
    'Bouffant',
    'Wiseacre',
    'Bramble',
    'Innocent III',
    'McPhail',
    'Artaud',
    'Bubblegum',
    'Goates',
    'Chatterjee',
    'Chen',
    'Spleenwort',
    'Limpet',
    'Badger',
    'Stopcock Sr.',
    'Turpentine',
    'Glaucous',
    'Petit-Soupçon',
    'Soupspoon',
    'Chinwag the Elder',
    'Clacque',
    'Djinn',
    'Jigglypuff',
    'いわゆるmonkey',
    'Dongfang Jr.',
    'Sòng-Táng',
    'MacDoogle',
    'Dornbusche',
    'Drexler-Chen',
    'Rathskeller',
    'Dunderfeld',
    'Belladonna',
    'E. Apfelgrüber',
    'Eberhardt',
    'Erdős',
    'Ibarra',
    'Ono',
    'le Carré',
    'Yamada',
    'Sweetcheeks',
    'Falkenwraithe',
    'Farnsworth',
    'Dickey',
    'Gravedigger',
    'Sepúlveda',
    'Glüm-Lorde II',
    'Gongsun-Huxley',
    'Grünwald-Singh',
    'Manne-Guy',
    'H. P. Merriwobble',
    'Janse van Rensburg',
    'Hoff-Witz',
    'His-Name-Is-Holy-Union',
    'Jesús y María',
    'Kande-Korn',
    'Kozłowski',
    'Kristjánsson',
    'Lefèvre',
    'Dybbuk',
    'Revenant',
    'Trpković',
    'Magdalena',
    'Castañeda',
    'De Tocqueville',
    'Mizuno',
    'Moriyama-Pipsworth',
    'Müller-Takemura',
    'Nibsworth',
    'Ramaswamy',
    'Pickle',
    'Plimpton',
    'Plum',
    'Babbet',
    'Clive Jr.',
    'Quartermaster',
    'Rambleford',
    'Renner-Tatterly',
    'Schnapps',
    'Schönbauer',
    'Mucklesford',
    'P. Tannenbaum',
    'Dogtooth',
    'Thistlewick',
    'Trundleby',
    'Bâlrog',
    'Widdersley',
    'Winterfrock',
    'St. Exupéry',
    'Santo Domingo',
    'Wolfsberger',
    'Cardamom',
    'Omicron 9000',
    'G.',
    'W.',
    'O.',
    'A.',
    'E.',
    'Pointe-à-Pitre',
    'Conscience',
    'Slackjaw',
    'San Carlos',
    'Boniface',
    'Wholehog',
    'Oyetunde',
    'Woolly',
    'Yum-Yum',
    'Perroquet',
    'Autruche',
    'Gleeful, D.D.S.',
    'Olawale',
    'St. Clare',
    'Escutcheon',
    'Busdriver',
    'Lovelady, Ph.D.',
    '“Ol’ Stink Eye” Ludgate',
    'Tibia',
    'Prime',
    'Nabob, Jr.',
    'Tub-Thumper',
    'Paladin',
    'Moneybags',
    'Moneypenny',
    'Suzerain',
    'Grandee',
    'Ōuyáng',
    'Nguyễn',
    'Phạm',
    'Satō',
    'Kṛṣṇamūrti',
    'Nāgārjuna',
  ];
})(typeof window !== 'undefined' ? window : globalThis);

/* 
Maestro
Penpusher
Balladeer
M. C.
*/
