/**
 * Paired lists for recipe editor presence monikers — keep in sync with random-name-generator.html.
 */
(function (global) {
  'use strict';

  global.NAME_DECK_LIST_A = [
    'Abbess',
    'Abbot',
    'Adept',
    'Administrator',
    'Admiral',
    'Archangel',
    'Archdeacon',
    'Archduke',
    'Archon',
    'Artificer',
    'Assistant to Ms.',
    'Attendant',
    'Bailiff',
    'Balladeer',
    'Beekeeper',
    'Bhagwan',
    'Boss Man',
    'Brother',
    'Bürgermeister',
    'Caliph',
    'Captain',
    'Cardinal',
    'Celebrity Impersonator',
    'Champion',
    'Chancellor',
    'Citizen',
    'Colonel',
    'Commander',
    'Commander-in-Exile',
    'Commodore',
    'Consort',
    'Constable',
    'Corporal',
    'Count',
    'Daddy',
    'Demiurge',
    'Den Mother',
    'Député',
    'Director',
    'Doña',
    'Duchess',
    'Elder',
    'Emperor',
    'Employee-of-the-Month',
    'Enfant Terrible',
    'Ensign',
    'Falconer',
    'Friar',
    'General',
    'Governor',
    'Grandee',
    'Groundskeeper',
    'Headmaster',
    'Headmistress',
    'Her Honour',
    'Her Majesty, Queen',
    'Herr',
    'His Grace, Pope',
    'Inmate',
    'Inquisitor',
    'Janissary',
    'Kid',
    'King Consort',
    'Lady',
    'Lady-in-Waiting',
    'Lieutenant',
    'Lil’ Guy',
    'M. C.',
    'Madame',
    'Mademoiselle',
    'Magistrate',
    'Major',
    'Marshal',
    'Master',
    'Mendicant',
    'Minor Deity',
    'Mistress',
    'Monsieur',
    'Monsignor',
    'Night Nurse',
    'Nurse',
    'Old Man',
    'Ombudsman',
    'Overseer',
    'Pallbearer',
    'Penitent',
    'Person-of-Interest',
    'Prefect',
    'Premier',
    'Prime Minister',
    'Prince',
    'Princess',
    'Professor',
    'Provost',
    'Quartermaster',
    'Queen Consort',
    'Queen Mother',
    'Regent',
    'Reverend',
    'Ringmaster',
    'Rabbi',
    'Saint',
    'Salvor',
    'Senator',
    'Señor',
    'Señora',
    'Señorita',
    'Sensei',
    'Sergeant',
    'Shri',
    'Sir',
    'Sister',
    'Squire',
    'Steward',
    'Sultan',
    'Superintendent',
    'Surveyor',
    'The Illustrious',
    'The Notorious',
    'The Right Honourable',
    'Tough Guy',
    'Troubadour',
    'Tsar',
    'Uncle',
    'Vicar',
    'Viceroy',
    'Viscount',
    'Vizier',
    'Warden',
    'Wazir',
  ];

  global.NAME_DECK_LIST_B = [
    '“Fatty” Hammerfist',
    '“Guvnor” Grapefield',
    '“Ol’ Stink Eye” Ludgate',
    '[Last Name Withheld]',
    'Abramov-Ping',
    'Ackbar',
    'Al-Farouq',
    'Al-Rashid',
    'Artaud',
    'Avrahami',
    'Babbet',
    'Badger',
    'Bâlrog',
    'Beancake',
    'Beekeeper',
    'Belladonna',
    'Bellringer',
    'Bisquick III',
    'Boniface',
    'Bouffant',
    'Bramble',
    'Bubblegum',
    'Cacahuète',
    'Cardamom',
    'Castañeda',
    'Chatterjee',
    'Chen',
    'Chinwag the Elder',
    'De Tocqueville',
    'Dickey',
    'Djinn',
    'Doe',
    'Dogtooth',
    'Dongfang Jr.',
    'Dornbusche',
    'Drexler-Chen',
    'Dunderfeld',
    'Dybbuk',
    'E. Apfelgrüber',
    'Eberhardt',
    'Erdős',
    'Escutcheon',
    'Farnsworth',
    'Glaucous',
    'Gleeful, D.D.S.',
    'Glüm-Lorde II',
    'Goates',
    'Gongsun-Huxley',
    'Grandee',
    'Gravedigger',
    'Grünwald-Singh',
    'H. P. Merriwobble',
    'Harari',
    'His-Name-Is-Holy-Union',
    'Ho',
    'Hoff-Witz',
    'Ibarra',
    'Innocent III',
    'Janse van Rensburg',
    'Jephthah',
    'Jesús y María',
    'Jigglypuff',
    'Kabibble',
    'Kande-Korn',
    'Kozłowski',
    'Krennic',
    'Kristjánsson',
    'Kṛṣṇamūrti',
    'le Carré',
    'Lefèvre',
    'Lovelady, Ph.D.',
    'MacDoogle',
    'Magdalena',
    'Manne-Guy',
    'Metatron',
    'McPhail',
    'Mizuno',
    'Moneybags',
    'Moneypenny',
    'Moriyama-Pipsworth',
    'Müller-Takemura',
    'Nabob, Jr.',
    'Nāgārjuna',
    'Naidoo',
    'Nguyễn',
    'Nibsworth',
    'O.',
    'Olawale',
    'Omicron 9000',
    'Ono',
    'Ōuyáng',
    'P. Tannenbaum',
    'Paladin',
    'Penpusher',
    'Perroquet',
    'Petit-Soupçon',
    'Phạm',
    'Pickles',
    'Plimpton',
    'Plum',
    'Prime',
    'Quartermaster',
    'Ramaswamy',
    'Rathskeller',
    'Ringleader',
    'Şahin',
    'San Carlos',
    'Santo Domingo',
    'Satō',
    'Von Schnapps',
    'Schleim',
    'Schönbauer',
    'Sell-Sword',
    'Sepúlveda',
    'Slackjaw',
    'Sòng-Táng',
    'Sørensen',
    'Soupspoon',
    'Spleenwort',
    'St. Exupéry',
    'Stopcock Sr.',
    'Strongarms',
    'Sweetcheeks',
    'T. Cakes',
    'Thistlewick',
    'Trpković',
    'Trundleby',
    'Turpentine',
    'Wholehog',
    'Widdersley',
    'Winterfrock',
    'Wiseacre',
    'Wolfsberger',
    'Woolly',
    'Yamamoto',
    'Yum-Yum',
    'いわゆるcookiefoot',
    'Zohar',
  ];
})(typeof window !== 'undefined' ? window : globalThis);
