/**
 * Paired lists for recipe editor presence monikers — keep in sync with random-name-generator.html.
 */
(function (global) {
  'use strict';

  global.NAME_DECK_LIST_A = [
    '',
    '',
    '',
    'A.',
    'Abbess',
    'Abbot',
    'Adept',
    'Administrator',
    'Admiral',
    'Advokat',
    'Archangel',
    'Archdeacon',
    'Archduke',
    'Archon',
    'Artificer',
    'Assistant to Ms.',
    'Attendant',
    'Baby Jane',
    'Bailiff',
    'Balladeer',
    'Beekeeper',
    'Bhagwan',
    'Boss Man',
    'Brother',
    'Bürgermeister',
    'Caliph',
    'Captain',
    'Cardinal',
    'Celebrity Impersonator',
    'Champion',
    'Chancellor',
    'Citizen',
    'Colonel',
    'Commander',
    'Commander-in-Exile',
    'Commodore',
    'Consort',
    'Constable',
    'Corporal',
    'Count',
    'Daddy',
    'Demiurge',
    'Den Mother',
    'Député',
    'Director',
    'Doña',
    'Duchess',
    'E.',
    'Elder',
    'Emperor',
    'Employee-of-the-Month',
    'Enfant Terrible',
    'Ensign',
    'Falconer',
    'Friar',
    'Funeral Singer',
    'G.',
    'General',
    'Governor',
    'Grandee',
    'Groundskeeper',
    'Headmaster',
    'Headmistress',
    'Her Honour',
    'Her Majesty, Queen',
    'Herr',
    'Hierophant',
    'His Grace, Pope',
    'Inmate',
    'Inquisitor',
    'Janissary',
    'Joe',
    'Kid',
    'King Consort',
    'Lady',
    'Lady-in-Waiting',
    'Librarian',
    'Lieutenant',
    'Lil’ Guy',
    'M.',
    'M. C.',
    'Madame',
    'Mademoiselle',
    'Magistrate',
    'Major',
    'Marshal',
    'Master',
    'Mendicant',
    'Minor Deity',
    'Mistress',
    'Monsieur',
    'Monsignor',
    'Night Nurse',
    'Nurse',
    'O.',
    'Old Man',
    'Ombudsman',
    'Overseer',
    'Oyabun',
    'P.',
    'Pallbearer',
    'Penitent',
    'Person-of-Interest',
    'Prefect',
    'Premier',
    'Prime Minister',
    'Prince',
    'Princess',
    'Professor',
    'Provost',
    'Quartermaster',
    'Queen Consort',
    'Queen Mother',
    'R.',
    'Regent',
    'Reverend',
    'Ringmaster',
    'Saint',
    'Salvor',
    'Senator',
    'Señor',
    'Señora',
    'Señorita',
    'Sensei',
    'Sergeant',
    'Shri',
    'Sir',
    'Sister',
    'Sovereign',
    'Squire',
    'Steward',
    'Sultan',
    'Summoner',
    'Superintendent',
    'Surveyor',
    'T.',
    'The Illustrious',
    'The Notorious',
    'The Right Honourable',
    'Tough Guy',
    'Troubadour',
    'Tsar',
    'Uncle',
    'Vicar',
    'Viceroy',
    'Viscount',
    'Vizier',
    'W.',
    'Warden',
    'Watchman',
    'Wazir',
  ];

  global.NAME_DECK_LIST_B = [
    '“Fatty” Hammerfist',
    '“Guvnor” Grapefield',
    '“Ol’ Stink Eye” Ludgate',
    '[Last Name Withheld]',
    'A.',
    'Abramov-Ping',
    'Ackbar',
    'Al-Farouq',
    'Al-Rashid',
    'Artaud',
    'Autruche',
    'Babbet',
    'Badger',
    'Bâlrog',
    'Beancake',
    'Beekeeper',
    'Belladonna',
    'Bellringer',
    'Bisquick III',
    'Boniface',
    'Bouffant',
    'Bramble',
    'Bubblegum',
    'Busdriver',
    'Campion',
    'Cardamom',
    'Castañeda',
    'Chatterjee',
    'Chen',
    'Chinwag the Elder',
    'Clacque',
    'Clive Jr.',
    'Conscience',
    'De Tocqueville',
    'Dickey',
    'Djinn',
    'Doe',
    'Dogtooth',
    'Dongfang Jr.',
    'Dornbusche',
    'Drexler-Chen',
    'Dunderfeld',
    'Dybbuk',
    'E.',
    'E. Apfelgrüber',
    'Eberhardt',
    'Erdős',
    'Escutcheon',
    'Falkenwraithe',
    'Farnsworth',
    'G.',
    'Glaucous',
    'Gleeful, D.D.S.',
    'Glüm-Lorde II',
    'Goates',
    'Gongsun-Huxley',
    'Grandee',
    'Gravedigger',
    'Grünwald-Singh',
    'H. P. Merriwobble',
    'His-Name-Is-Holy-Union',
    'Ho',
    'Hoff-Witz',
    'Ibarra',
    'Innocent III',
    'Janse van Rensburg',
    'Jephthah',
    'Jesús y María',
    'Jigglypuff',
    'Kande-Korn',
    'Kozłowski',
    'Krennic',
    'Kristjánsson',
    'Kṛṣṇamūrti',
    'le Carré',
    'Lefèvre',
    'Limpet',
    'Lovelady, Ph.D.',
    'MacDoogle',
    'Magdalena',
    'Manne-Guy',
    'McPhail',
    'Mizuno',
    'Moneybags',
    'Moneypenny',
    'Moriyama-Pipsworth',
    'Moue',
    'Mucklesford',
    'Müller-Takemura',
    'Nabob, Jr.',
    'Nāgārjuna',
    'Naidoo',
    'Nguyễn',
    'Nibsworth',
    'O.',
    'Olawale',
    'Omicron 9000',
    'Ono',
    'Ōuyáng',
    'Oyetunde',
    'P. Dunwitty',
    'P. Tannenbaum',
    'Paladin',
    'Penpusher',
    'Perroquet',
    'Petit-Soupçon',
    'Phạm',
    'Pickle',
    'Plimpton',
    'Plum',
    'Pointe-à-Pitre',
    'Prime',
    'Quartermaster',
    'Ramaswamy',
    'Rambleford',
    'Rathskeller',
    'Renner-Tatterly',
    'Revenant',
    'Ringleader',
    'Şahin',
    'San Carlos',
    'Santo Domingo',
    'Satō',
    'Schnapps',
    'Schönbauer',
    'Sell-Sword',
    'Sepúlveda',
    'Slackjaw',
    'Sòng-Táng',
    'Sørensen',
    'Soupspoon',
    'Spleenwort',
    'St. Clare',
    'St. Exupéry',
    'Stopcock Sr.',
    'Strongarm',
    'Suzerain',
    'Sweetcheeks',
    'T. Cakes',
    'Thistlewick',
    'Tibia',
    'Trpković',
    'Trundleby',
    'Tub-Thumper',
    'Turpentine',
    'W.',
    'Wholehog',
    'Widdersley',
    'Winterfrock',
    'Wiseacre',
    'Wolfsberger',
    'Woolly',
    'Yamamoto',
    'Yum-Yum',
    'いわゆるmonkey',
  ];
})(typeof window !== 'undefined' ? window : globalThis);
