-- Shopping grammar: mark curated substance/mass-style catalog items (see thread).

update catalog.ingredients
set is_mass_noun = true
where name in (
  'allspice',
  'almond butter',
  'aluminum foil',
  'arugula',
  'asparagus',
  'baba ghanoush',
  'baking powder',
  'basil',
  'BBQ sauce',
  'black pepper',
  'black salt',
  'bok choy',
  'bread',
  'broccoli',
  'broth',
  'butter',
  'canned tomato',
  'cardamom',
  'cat food',
  'cat litter',
  'catsup',
  'cauliflower',
  'celery',
  'cereal',
  'chuck',
  'cilantro',
  'cinnamon',
  'cleaner',
  'coffee',
  'coriander',
  'corn',
  'cornstarch',
  'cream cheese',
  'cumin',
  'date syrup',
  'deodorant',
  'dill',
  'dish soap',
  'edamame',
  'epsom salt',
  'fenugreek',
  'flour',
  'focaccia',
  'furikake',
  'garlic',
  'garlic powder',
  'ginger',
  'ginger powder',
  'gnocchi',
  'granola',
  'honey',
  'hot sauce',
  'hummus',
  'ice cream',
  'jam',
  'Just Egg',
  'kale',
  'lettuce',
  'liquid smoke',
  'macadamia milk',
  'maple syrup',
  'marinara sauce',
  'mayonnaise',
  'mint',
  'muesli',
  'mustard',
  'nocciolata',
  'nut butter',
  'nutmeg',
  'nutritional yeast',
  'oat milk',
  'oatmeal',
  'oil',
  'olive oil',
  'onion powder',
  'orange juice',
  'oregano',
  'paprika',
  'parchment',
  'parmesan',
  'parsley',
  'pasta',
  'pineapple',
  'pineapple juice',
  'pistachio butter',
  'puff pastry',
  'quinoa',
  'ramen',
  'rice',
  'rosemary',
  'saffron',
  'salsa',
  'salt',
  'sausage',
  'seaweed',
  'sesame oil',
  'shampoo',
  'soap',
  'sour cream',
  'soy sauce',
  'spice mix',
  'spinach',
  'sugar',
  'tea',
  'tempeh',
  'thyme',
  'tofu',
  'toilet paper',
  'tomato paste',
  'toothpaste',
  'turmeric',
  'vinegar',
  'wasabi paste',
  'waxed paper',
  'wine',
  'Worcestershire sauce',
  'yogurt'
);
