-- Store linked subrecipes as recipe structure, not catalog ingredients.
-- This migration is intentionally forward-only: existing linked-recipe rows
-- must be removed before applying so no legacy RIM backfill is required.

do $$
begin
  if exists (
    select 1
      from catalog.recipe_ingredient_map rim
     where coalesce(rim.is_recipe, false) = true
       and rim.linked_recipe_id is not null
       and rim.linked_recipe_id > 0
       and rim.linked_recipe_id <> rim.recipe_id
  ) then
    raise exception 'recipe_subrecipe_links migration requires zero legacy linked-subrecipe rows';
  end if;
end $$;

create table if not exists catalog.recipe_subrecipe_links (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references catalog.recipes(id) on delete cascade,
  section_id bigint references catalog.recipe_sections(id),
  sort_order integer,
  quantity text,
  quantity_min double precision,
  quantity_max double precision,
  quantity_is_approx boolean not null default false,
  unit text not null default '',
  prep_notes text not null default '',
  is_optional boolean not null default false,
  parenthetical_note text not null default '',
  linked_recipe_id bigint not null references catalog.recipes(id),
  recipe_text text not null default '',
  is_alt boolean not null default false,
  constraint recipe_subrecipe_links_not_self_check
    check (linked_recipe_id <> recipe_id)
);

create index if not exists recipe_subrecipe_links_recipe_sort_idx
  on catalog.recipe_subrecipe_links (recipe_id, sort_order, id);

create index if not exists recipe_subrecipe_links_linked_recipe_idx
  on catalog.recipe_subrecipe_links (linked_recipe_id);

alter table catalog.recipe_subrecipe_links enable row level security;

drop policy if exists catalog_allow_all_recipe_subrecipe_links
  on catalog.recipe_subrecipe_links;

create policy catalog_allow_all_recipe_subrecipe_links
  on catalog.recipe_subrecipe_links
  for all
  to anon, authenticated
  using (true)
  with check (true);

grant all on table catalog.recipe_subrecipe_links to anon, authenticated;
grant usage, select on sequence catalog.recipe_subrecipe_links_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1
      from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'catalog'
       and tablename = 'recipe_subrecipe_links'
  ) then
    alter publication supabase_realtime add table catalog.recipe_subrecipe_links;
  end if;
end $$;

create or replace function catalog.save_recipe(recipe_payload jsonb)
returns jsonb
language plpgsql
set search_path = catalog, public
as $$
declare
  v_recipe_id bigint;
  v_servings jsonb;
  v_tag jsonb;
  v_tag_name text;
  v_tag_id bigint;
  v_tag_sort integer := 1;
  v_tag_max_sort integer;
  v_step jsonb;
  v_heading jsonb;
  v_heading_id bigint;
  v_kept_heading_ids bigint[] := array[]::bigint[];
  v_ing jsonb;
  v_map_id bigint;
  v_ingredient_id bigint;
  v_ingredient_name text;
  v_canonical_name text;
  v_unit text;
  v_qty_text text;
  v_qty_num double precision;
  v_kept_map_ids bigint[] := array[]::bigint[];
  v_next_unit_sort integer;
  v_subrecipe jsonb;
  v_subrecipe_link_id bigint;
  v_subrecipe_linked_recipe_id bigint;
  v_kept_subrecipe_link_ids bigint[] := array[]::bigint[];
begin
  v_recipe_id := nullif(recipe_payload->>'id', '')::bigint;
  if v_recipe_id is null or v_recipe_id <= 0 then
    raise exception 'saveRecipe: valid recipe id is required';
  end if;

  if not exists (select 1 from recipes where id = v_recipe_id) then
    raise exception 'saveRecipe: recipe % does not exist', v_recipe_id;
  end if;

  v_servings := coalesce(recipe_payload->'servings', '{}'::jsonb);

  update recipes
     set title = coalesce(recipe_payload->>'title', ''),
         summary = btrim(coalesce(recipe_payload->>'summary', '')),
         servings_default = nullif(v_servings->>'default', '')::numeric,
         servings_min = nullif(v_servings->>'min', '')::numeric,
         servings_max = nullif(v_servings->>'max', '')::numeric
   where id = v_recipe_id;

  delete from recipe_tag_map where recipe_id = v_recipe_id;

  for v_tag in select * from jsonb_array_elements(coalesce(recipe_payload->'tags', '[]'::jsonb))
  loop
    v_tag_name := btrim(v_tag #>> '{}');
    if v_tag_name = '' then
      continue;
    end if;

    select id into v_tag_id
      from tags
     where lower(btrim(name::text)) = lower(v_tag_name)
     limit 1;

    if v_tag_id is null then
      select coalesce(max(sort_order), 0) + 1 into v_tag_max_sort from tags;
      insert into tags (name, is_hidden, sort_order, intended_use)
      values (v_tag_name, false, v_tag_max_sort, 'recipes')
      returning id into v_tag_id;
    end if;

    insert into recipe_tag_map (recipe_id, tag_id, sort_order)
    values (v_recipe_id, v_tag_id, v_tag_sort)
    on conflict (recipe_id, tag_id) do update
      set sort_order = excluded.sort_order;

    v_tag_sort := v_tag_sort + 1;
    v_tag_id := null;
  end loop;

  delete from recipe_steps where recipe_id = v_recipe_id;

  for v_step in select * from jsonb_array_elements(coalesce(recipe_payload->'steps', '[]'::jsonb))
  loop
    insert into recipe_steps (recipe_id, step_number, instructions, type)
    values (
      v_recipe_id,
      nullif(v_step->>'step_number', '')::integer,
      coalesce(v_step->>'instructions', ''),
      nullif(v_step->>'type', '')
    );
  end loop;

  for v_heading in select * from jsonb_array_elements(coalesce(recipe_payload->'headings', '[]'::jsonb))
  loop
    v_heading_id := nullif(v_heading->>'id', '')::bigint;

    if v_heading_id is not null
       and exists (
         select 1 from recipe_ingredient_headings
          where id = v_heading_id and recipe_id = v_recipe_id
       ) then
      update recipe_ingredient_headings
         set section_id = nullif(v_heading->>'section_id', '')::bigint,
             sort_order = nullif(v_heading->>'sort_order', '')::integer,
             heading_text = coalesce(v_heading->>'heading_text', '')
       where id = v_heading_id
         and recipe_id = v_recipe_id;
    else
      insert into recipe_ingredient_headings
        (recipe_id, section_id, sort_order, heading_text)
      values (
        v_recipe_id,
        nullif(v_heading->>'section_id', '')::bigint,
        nullif(v_heading->>'sort_order', '')::integer,
        coalesce(v_heading->>'heading_text', '')
      )
      returning id into v_heading_id;
    end if;

    v_kept_heading_ids := array_append(v_kept_heading_ids, v_heading_id);
  end loop;

  delete from recipe_ingredient_headings
   where recipe_id = v_recipe_id
     and not (id = any(v_kept_heading_ids));

  for v_ing in select * from jsonb_array_elements(coalesce(recipe_payload->'ingredients', '[]'::jsonb))
  loop
    v_map_id := nullif(v_ing->>'id', '')::bigint;
    v_ingredient_id := null;
    v_canonical_name := '';
    v_unit := btrim(coalesce(v_ing->>'unit', ''));
    v_ingredient_name := btrim(coalesce(v_ing->>'ingredient_name', ''));
    if v_ingredient_name = '' then
      continue;
    end if;

    if v_unit <> '' then
      select coalesce(max(sort_order), 0) + 1 into v_next_unit_sort from units;
      insert into units
        (code, name_singular, name_plural, category, sort_order, is_hidden, is_removed)
      values (v_unit, v_unit, '', '', v_next_unit_sort, false, false)
      on conflict (code) do nothing;
    end if;

    select id, name into v_ingredient_id, v_canonical_name
      from ingredients
     where lower(btrim(name)) = lower(v_ingredient_name)
     limit 1;

    if v_ingredient_id is null then
      select i.id, i.name into v_ingredient_id, v_canonical_name
        from ingredient_synonyms s
        join ingredients i on i.id = s.ingredient_id
       where lower(btrim(s.synonym::text)) = lower(v_ingredient_name)
       limit 1;
    end if;

    if v_ingredient_id is null then
      insert into ingredients (name, lemma)
      values (v_ingredient_name, nullif(v_ing->>'ingredient_lemma', ''))
      returning id, name into v_ingredient_id, v_canonical_name;

      insert into ingredient_variants
        (ingredient_id, variant, sort_order, home_location, is_deprecated)
      values (v_ingredient_id, 'default', 0, 'none', false);
    end if;

    v_qty_text := coalesce(v_ing->>'quantity', '');
    v_qty_num := case
      when v_qty_text ~ '^\s*-?([0-9]+(\.[0-9]+)?|\.[0-9]+)\s*$'
        then v_qty_text::double precision
      else null
    end;
    if v_qty_num is not null and v_qty_num <= 0 then
      v_qty_text := '';
    end if;

    if v_map_id is not null
       and exists (
         select 1 from recipe_ingredient_map
          where id = v_map_id and recipe_id = v_recipe_id
       ) then
      update recipe_ingredient_map
         set ingredient_id = v_ingredient_id,
             section_id = nullif(v_ing->>'section_id', '')::bigint,
             quantity = v_qty_text,
             unit = v_unit,
             prep_notes = btrim(coalesce(v_ing->>'prep_notes', '')),
             is_optional = coalesce((v_ing->>'is_optional')::boolean, false),
             subrecipe_id = null,
             sort_order = nullif(v_ing->>'sort_order', '')::integer,
             parenthetical_note = btrim(coalesce(v_ing->>'parenthetical_note', '')),
             quantity_min = nullif(v_ing->>'quantity_min', '')::double precision,
             quantity_max = nullif(v_ing->>'quantity_max', '')::double precision,
             quantity_is_approx = coalesce((v_ing->>'quantity_is_approx')::boolean, false),
             linked_recipe_id = null,
             recipe_text = '',
             is_recipe = false,
             is_alt = coalesce((v_ing->>'is_alt')::boolean, false),
             display_name = case
               when lower(btrim(coalesce(v_ing->>'ingredient_name', ''))) = lower(btrim(coalesce(v_canonical_name, ''))) then null
               else btrim(coalesce(v_ing->>'ingredient_name', ''))
             end,
             variant = btrim(coalesce(v_ing->>'variant', '')),
             size = btrim(coalesce(v_ing->>'size', ''))
       where id = v_map_id
         and recipe_id = v_recipe_id;
    else
      insert into recipe_ingredient_map
        (
          recipe_id, ingredient_id, section_id, quantity, unit, prep_notes,
          is_optional, subrecipe_id, sort_order, parenthetical_note,
          quantity_min, quantity_max, quantity_is_approx, linked_recipe_id,
          recipe_text, is_recipe, is_alt, display_name, variant, size
        )
      values
        (
          v_recipe_id,
          v_ingredient_id,
          nullif(v_ing->>'section_id', '')::bigint,
          v_qty_text,
          v_unit,
          btrim(coalesce(v_ing->>'prep_notes', '')),
          coalesce((v_ing->>'is_optional')::boolean, false),
          null,
          nullif(v_ing->>'sort_order', '')::integer,
          btrim(coalesce(v_ing->>'parenthetical_note', '')),
          nullif(v_ing->>'quantity_min', '')::double precision,
          nullif(v_ing->>'quantity_max', '')::double precision,
          coalesce((v_ing->>'quantity_is_approx')::boolean, false),
          null,
          '',
          false,
          coalesce((v_ing->>'is_alt')::boolean, false),
          case
            when lower(btrim(coalesce(v_ing->>'ingredient_name', ''))) = lower(btrim(coalesce(v_canonical_name, ''))) then null
            else btrim(coalesce(v_ing->>'ingredient_name', ''))
          end,
          btrim(coalesce(v_ing->>'variant', '')),
          btrim(coalesce(v_ing->>'size', ''))
        )
      returning id into v_map_id;
    end if;

    v_kept_map_ids := array_append(v_kept_map_ids, v_map_id);
  end loop;

  delete from recipe_ingredient_map
   where recipe_id = v_recipe_id
     and not (id = any(v_kept_map_ids));

  for v_subrecipe in select * from jsonb_array_elements(coalesce(recipe_payload->'subrecipes', '[]'::jsonb))
  loop
    v_subrecipe_link_id := nullif(v_subrecipe->>'id', '')::bigint;
    v_subrecipe_linked_recipe_id := nullif(v_subrecipe->>'linked_recipe_id', '')::bigint;
    v_unit := btrim(coalesce(v_subrecipe->>'unit', ''));

    if v_subrecipe_linked_recipe_id is null
       or v_subrecipe_linked_recipe_id <= 0
       or v_subrecipe_linked_recipe_id = v_recipe_id
       or not exists (select 1 from recipes where id = v_subrecipe_linked_recipe_id) then
      continue;
    end if;

    if v_unit <> '' then
      select coalesce(max(sort_order), 0) + 1 into v_next_unit_sort from units;
      insert into units
        (code, name_singular, name_plural, category, sort_order, is_hidden, is_removed)
      values (v_unit, v_unit, '', '', v_next_unit_sort, false, false)
      on conflict (code) do nothing;
    end if;

    v_qty_text := coalesce(v_subrecipe->>'quantity', '');
    v_qty_num := case
      when v_qty_text ~ '^\s*-?([0-9]+(\.[0-9]+)?|\.[0-9]+)\s*$'
        then v_qty_text::double precision
      else null
    end;
    if v_qty_num is not null and v_qty_num <= 0 then
      v_qty_text := '';
    end if;

    if v_subrecipe_link_id is not null
       and exists (
         select 1 from recipe_subrecipe_links
          where id = v_subrecipe_link_id and recipe_id = v_recipe_id
       ) then
      update recipe_subrecipe_links
         set section_id = nullif(v_subrecipe->>'section_id', '')::bigint,
             sort_order = nullif(v_subrecipe->>'sort_order', '')::integer,
             quantity = v_qty_text,
             quantity_min = nullif(v_subrecipe->>'quantity_min', '')::double precision,
             quantity_max = nullif(v_subrecipe->>'quantity_max', '')::double precision,
             quantity_is_approx = coalesce((v_subrecipe->>'quantity_is_approx')::boolean, false),
             unit = v_unit,
             prep_notes = btrim(coalesce(v_subrecipe->>'prep_notes', '')),
             is_optional = coalesce((v_subrecipe->>'is_optional')::boolean, false),
             parenthetical_note = btrim(coalesce(v_subrecipe->>'parenthetical_note', '')),
             linked_recipe_id = v_subrecipe_linked_recipe_id,
             recipe_text = btrim(coalesce(v_subrecipe->>'recipe_text', '')),
             is_alt = coalesce((v_subrecipe->>'is_alt')::boolean, false)
       where id = v_subrecipe_link_id
         and recipe_id = v_recipe_id;
    else
      insert into recipe_subrecipe_links
        (
          recipe_id, section_id, sort_order, quantity, quantity_min, quantity_max,
          quantity_is_approx, unit, prep_notes, is_optional, parenthetical_note,
          linked_recipe_id, recipe_text, is_alt
        )
      values
        (
          v_recipe_id,
          nullif(v_subrecipe->>'section_id', '')::bigint,
          nullif(v_subrecipe->>'sort_order', '')::integer,
          v_qty_text,
          nullif(v_subrecipe->>'quantity_min', '')::double precision,
          nullif(v_subrecipe->>'quantity_max', '')::double precision,
          coalesce((v_subrecipe->>'quantity_is_approx')::boolean, false),
          v_unit,
          btrim(coalesce(v_subrecipe->>'prep_notes', '')),
          coalesce((v_subrecipe->>'is_optional')::boolean, false),
          btrim(coalesce(v_subrecipe->>'parenthetical_note', '')),
          v_subrecipe_linked_recipe_id,
          btrim(coalesce(v_subrecipe->>'recipe_text', '')),
          coalesce((v_subrecipe->>'is_alt')::boolean, false)
        )
      returning id into v_subrecipe_link_id;
    end if;

    v_kept_subrecipe_link_ids := array_append(v_kept_subrecipe_link_ids, v_subrecipe_link_id);
  end loop;

  delete from recipe_subrecipe_links
   where recipe_id = v_recipe_id
     and not (id = any(v_kept_subrecipe_link_ids));

  return jsonb_build_object('id', v_recipe_id);
end;
$$;

grant execute on function catalog.save_recipe(jsonb) to anon, authenticated;
